name: test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    strategy:
      matrix:
        otp: ['27.0.0.0']
        elixir: ['1.17']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
